name: Snyk PHP Security Scan

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Validar Composer
        run: composer validate

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist

      - name: Instalar Snyk CLI
        run: npm install -g snyk

      - name: Autenticar no Snyk
        run: snyk auth ${{ secrets.SECRET_SNYK }}

      - name: Executar scan Snyk
        run: snyk test --file=composer.lock

      - name: Monitorar projeto
        run: snyk monitor --file=composer.lock